name: Continuous Integration
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      - name: Install dependencies
        run: npm ci

      # - name: Run tests on library # TODO: enable tests
      #   run: npm run test:lib -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Build
        run: npm run build

      # - name: Run tests on demo app # TODO: enable tests
      #   run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Write .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - name: Publish to npm
        working-directory: ./dist/bottom-nav
        run: npm publish
