name: Release v9
on:
  push:
    branches:
      - releases/v9.*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          registry-url: 'https://registry.npmjs.org/'

      - run: npm install

      - name: run linter
        run: npm run lint

      - name: build library
        run: npm run build -- --prod

      # - name: run library tests
      #   run: npm run test

      # - name: run demo tests
      #   run: npm run test:demo

      - name: copy README and LICENSE
        run: |
          cp LICENSE dist/ngx-bottom-nav
          cp README.md dist/ngx-bottom-nav

      - name: publish to npm
        working-directory: ./dist/ngx-bottom-nav
        run: npm publish --tag v9
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
